module ImportExpectations
  def self.absence_record
    {
      'Record Type' => 'ABA',
      'PersonID' => 'A48180',
      'Absence AttendanceID' => '112119701A',
      'Absence Type' => 'Special Increasing Bal',
      'Absence Reason' => "Carer's Leave",
      'Status' => nil,
      'Notification Date' => Date.new(2019, 1, 2),
      'Projected StartDate' => Date.new(2018, 12, 6),
      'Projected StartTime' => nil,
      'Projected EndDate' => Date.new(2018, 12, 6),
      'Projected EndTime' => nil,
      'Actual StartDate' => Date.new(2018, 12, 6),
      'Actual StartTime' => nil,
      'Actual EndDate' => Date.new(2018, 12, 6),
      'Actual EndTime' => nil,
      'Sickness StartDate' => Date.new(2018, 12, 6),
      'Sickness DateEnd' => Date.new(2018, 12, 6),
      'Absence Duration Days' => '1',
      'Absence Duration Hours' => nil,
      'Absence Units' => 'D',
      'Hours Lost' => '7.5',
      'Sessions Lost' => '1',
      'Work Related' => 'No',
      'Third Party' => nil,
      'Disability Related' => nil,
      'Violence AggressionRelated' => nil,
      'Notifyable Disease' => nil,
      'Returntowork discussiondate' => Date.new(2018, 12, 6),
      'OccupationalHealth referralDate' => Date.new(2018, 12, 6),
      'Last UpdateDate' => Time.new(2020, 4, 7, 14, 53, 54),
      'Surgery Related' => nil,
      'DH Monitoring' => nil,
      'Sickness Reason' => nil,
      '3rdParty SystemReference' => '726999',
      'Ins_Upd_TimeStamp' => Time.new(2020, 4, 7, 14, 53, 54)
    }.freeze
  end

  def self.person_record
    {
      'Record Type' => 'PRA',
      'PersonID' => 'A48180',
      'Effective StartDate' => Date.new(2017, 5, 1),
      'Effective EndDate' => Date.new(2020, 5, 1),
      'Employee Number' => '102598012',
      'Title' => 'Mr.',
      'LastName' => 'sname',
      'FirstName' => 'fname',
      'MiddleNames' => 'fname',
      'MaidenName' => 'sname',
      'Previous LastName' => 'sname',
      'Gender' => 'Female',
      'Date of Birth' => Date.new(1986, 8, 1),
      'NationalInsurance Number' => 'AB012201B',
      'NHS UniqueID' => '289601',
      'HireDate' => Date.new(2004, 6, 1),
      'ActualTermination Date' => Date.new(2020, 5, 1),
      'Termination Reason' => nil,
      'Employee StatusFlag' => 'E',
      'WTR Opt Out' => nil,
      'WTR Opt Out Date' => Date.new(2020, 5, 1),
      'Ethnic Origin' => 'British',
      'Country of Birth' => 'United Kingdom',
      'Previous Employer' => 'OXLEAS NHS TRUST',
      'Previous EmployerType' => 'Unknown',
      'CSD 3 Months' => Date.new(2003, 7, 1),
      'CSD 12 Months' => Date.new(2004, 4, 1),
      'NHS CRS UUID' => nil,
      'System Person Type' => 'EMP',
      'User Person Type' => 'Employee.Ex-Applicant',
      'Office e-mail address' => 'john.smith@example.com',
      'NHS StartDate' => Date.new(2003, 7, 1),
      'Last UpdateDate' => Date.new(2017, 5, 1),
      'Disability Flag' => 'N'
    }.freeze
  end

  def self.position_record
    {
      'Record Type' => 'POA',
      'PositionID' => 'ABC4401',
      'Effective FromDate' => Date.new(2019, 4, 22),
      'Effective ToDate' => nil,
      'Position Number' => 'ABC5001',
      'Position Name' => 'ABC5001|Core Trainee|001|',
      'Budgeted FTE' => '3.53',
      'Subjective Code' => 'ABC2101',
      'Job StaffGroup' => 'Medical and Dental',
      'Job Role' => 'Specialty Registrar',
      'Occupation Code' => '001',
      'Payscale' => 'MN31',
      'Grade Step' => 'MN31|0',
      'ISA Regulated Post' => 'Not Applicable',
      'Organisation ID' => '52001',
      'Hiring Status' => 'Active',
      'Position Type' => 'NONE',
      'Workplace OrgCode' => nil,
      'Last UpdateDate' => Time.new(2019, 10, 3, 12, 17, 1),
      'Subjective CodeDescription' => 'RT Doctor'
    }.freeze
  end
end
