# Import some test data for demonstration purposes.
FakeDataJob.perform_later(klass: 'AbsenceRecord', quantity: 500)
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_assignment_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_competency_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_costing_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_disability_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_element_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_location_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_organisation_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_person_eit_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_person_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_position_eit_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_position_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_qualification_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_sit_record.DAT')
ImportFileJob.perform_later(filename: 'spec/fixtures/files/good_imports/add_training_absence_record.DAT')
