# Import some test data for demonstration purposes.
FakeDataJob.perform_later(klass: 'AbsenceRecord', quantity: 500)
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_assignment_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_competency_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_costing_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_disability_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_element_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_location_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_organisation_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_person_eit_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_person_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_position_eit_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_position_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_qualification_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_sit_record.dsv')
DailyImportJob.perform_later(filename: 'spec/fixtures/files/add_training_absence_record.dsv')
