class AddAllFieldsToPersonRecords < ActiveRecord::Migration[6.0]
  def change
    change_table :person_records, bulk: true do |t|
      t.string 'Record Type'
      t.string 'Effective StartDate'
      t.string 'Effective EndDate'
      t.string 'Employee Number'
      t.string 'Title'
      t.string 'LastName'
      t.string 'FirstName'
      t.string 'MiddleNames'
      t.string 'MaidenName'
      t.string 'PreferredName'
      t.string 'Previous LastName'
      t.string 'Gender'
      t.string 'Date of Birth'
      t.string 'NationalInsurance Number'
      t.string 'NHS UniqueID'
      t.string 'HireDate'
      t.string 'ActualTermination Date'
      t.string 'Termination Reason'
      t.string 'Employee StatusFlag'
      t.string 'WTR Opt Out'
      t.string 'WTR Opt Out Date'
      t.string 'Ethnic Origin'
      t.string 'Country of Birth'
      t.string 'Previous Employer'
      t.string 'Previous EmployerType'
      t.string 'CSD 3 Months'
      t.string 'CSD 12 Months'
      t.string 'NHS CRS UUID'
      t.string 'System Person Type'
      t.string 'User Person Type'
      t.string 'Office e-mail address'
      t.string 'NHS StartDate'
      t.string 'Last UpdateDate'
      t.string 'Disability Flag'
      t.string 'Ins_Upd_TimeStamp'
    end
  end
end
