class CreatePersonEitRecords < ActiveRecord::Migration[6.0]
  def change
    create_table :person_eit_records do |t|
      t.string 'Person ID'
      t.string 'Person Extra Information ID'
      t.string 'Information Type'
      t.string 'PEI_INFORMATION_CATEGORY'
      t.string 'PEI_INFORMATION1'
      t.string 'PEI_INFORMATION2'
      t.string 'PEI_INFORMATION3'
      t.string 'PEI_INFORMATION4'
      t.string 'PEI_INFORMATION5'
      t.string 'PEI_INFORMATION6'
      t.string 'PEI_INFORMATION7'
      t.string 'PEI_INFORMATION8'
      t.string 'PEI_INFORMATION9'
      t.string 'PEI_INFORMATION10'
      t.string 'PEI_INFORMATION11'
      t.string 'PEI_INFORMATION12'
      t.string 'PEI_INFORMATION13'
      t.string 'PEI_INFORMATION14'
      t.string 'PEI_INFORMATION15'
      t.string 'PEI_INFORMATION16'
      t.string 'PEI_INFORMATION17'
      t.string 'PEI_INFORMATION18'
      t.string 'PEI_INFORMATION19'
      t.string 'PEI_INFORMATION20'
      t.string 'PEI_INFORMATION21'
      t.string 'PEI_INFORMATION22'
      t.string 'PEI_INFORMATION23'
      t.string 'PEI_INFORMATION24'
      t.string 'PEI_INFORMATION25'
      t.string 'PEI_INFORMATION26'
      t.string 'PEI_INFORMATION27'
      t.string 'PEI_INFORMATION28'
      t.string 'PEI_INFORMATION29'
      t.string 'PEI_INFORMATION30'
      t.string 'ATTRIBUTE_CATEGORY'
      t.string 'PEI_ATTRIBUTE1'
      t.string 'PEI_ATTRIBUTE2'
      t.string 'PEI_ATTRIBUTE3'
      t.string 'PEI_ATTRIBUTE4'
      t.string 'PEI_ATTRIBUTE5'
      t.string 'PEI_ATTRIBUTE6'
      t.string 'PEI_ATTRIBUTE7'
      t.string 'PEI_ATTRIBUTE8'
      t.string 'PEI_ATTRIBUTE9'
      t.string 'PEI_ATTRIBUTE10'
      t.string 'PEI_ATTRIBUTE11'
      t.string 'PEI_ATTRIBUTE12'
      t.string 'PEI_ATTRIBUTE13'
      t.string 'PEI_ATTRIBUTE14'
      t.string 'PEI_ATTRIBUTE15'
      t.string 'PEI_ATTRIBUTE16'
      t.string 'PEI_ATTRIBUTE17'
      t.string 'PEI_ATTRIBUTE18'
      t.string 'PEI_ATTRIBUTE19'
      t.string 'PEI_ATTRIBUTE20'
      t.timestamp 'Last Update Date'

      t.timestamps
    end

    add_index :person_eit_records, ['Person Extra Information ID'], unique: true
  end
end

